// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rpc "github.com/jh-chee/kitewave/rpc-server/kitex_gen/rpc"
	mock "github.com/stretchr/testify/mock"
)

// IMService is an autogenerated mock type for the IMService type
type IMService struct {
	mock.Mock
}

// Pull provides a mock function with given fields: ctx, req
func (_m *IMService) Pull(ctx context.Context, req *rpc.PullRequest) (*rpc.PullResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *rpc.PullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.PullRequest) (*rpc.PullResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.PullRequest) *rpc.PullResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.PullResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rpc.PullRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: ctx, req
func (_m *IMService) Send(ctx context.Context, req *rpc.SendRequest) (*rpc.SendResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *rpc.SendResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.SendRequest) (*rpc.SendResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.SendRequest) *rpc.SendResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.SendResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rpc.SendRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIMService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMService creates a new instance of IMService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMService(t mockConstructorTestingTNewIMService) *IMService {
	mock := &IMService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
